import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from './../styles/Home.module.scss'
import { SideBar } from './components/sidebar'
import { PersonalInfo } from './components/personalInfo'
import { useContext } from 'react'
import { MyContext } from '../context/mycontext'
import { SelectPlan } from './components/selectPlan'
import { Addons } from './components/addons'
import { Summary } from './components/summary'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const { step }: any = useContext(MyContext);


  const SelectStep = () => {
    switch (step) {
      case 1:
        return <PersonalInfo></PersonalInfo>
        break;
      case 2:
        return <SelectPlan></SelectPlan>
        break;
      case 3:
        return <Addons></Addons>
        break;
      case 4:
        return <Summary></Summary>
        break;
    }
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.containerLeft}>
          <SideBar />
        </div>
        <div className={styles.containerRight}>
          <SelectStep></SelectStep>
        </div>
      </main>
    </>
  )
}
