import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from './../styles/Home.module.scss'
import { SideBar } from './components/sidebar'
import { PersonalInfo } from './components/personalInfo'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.containerLeft}>
          <SideBar />
        </div>
        <div className={styles.containerRight}>
          <PersonalInfo></PersonalInfo>
        </div>
      </main>
    </>
  )
}
